dataset_name: lis_01_all_subjects_male
output_group: medicated_adhd_vs_controls/lis
subject_col: study_id
selection_metric: separation_logreg_balanced_accuracy
selection_eval_name: med_adhd_vs_ctrl
conditions:
- EO_baseline
- EC_baseline
run_pooled: true
ignore_annotations: true
use_derivatives: true
interactive: true
save_static_figures: true
compress_viz_with_pca: true
reducers:
  - PCA
  - UMAP
n_components_sweep:
- 2
- 3
- 5
- 10
- 15
- 20
- 25
group_filters:
- adhd:
  - 0
  psychostimulant:
  - 0
- adhd:
  - 1
  psychostimulant:
  - 1
  psychostimulant_category:
  - Lisdexamfetamine
filter_col:
- sex
- age_group
filter_val:
- - M
- - 5-8
  - 9-12
  - 13-18
evals:
- name: med_adhd_vs_ctrl
  target_col: combined_diagnosis
  label_map:
    Control: '0'
    Epilepsy: '0'
    ASD: '0'
    ASD+Epilepsy: '0'
    ADHD: '1'
    ADHD+Epilepsy: '1'
    ADHD+ASD: '1'
    ADHD+ASD+Epilepsy: '1'
- name: age_separation
  target_col: age_group
- name: condition_separation
  target_col: condition
  group_col: patient_group_id
