"""Configuration constants for EEG QC annotation handling."""

from __future__ import annotations

import re
from typing import Dict, Tuple

from .config import (
    EYES_CLOSED_LABELS,
    EYES_OPEN_LABELS,
    HV_LABELS,
    PHOTO_LABELS,
    POST_HV_LABELS,
)

# Frequency bands for PSD summaries
BAND_LIMITS: Dict[str, Tuple[int, int]] = {
    "delta": (1, 4),
    "theta": (4, 8),
    "alpha": (8, 12),
    "beta": (12, 30),
    "gamma": (30, 45),
}

# 10-20 montage channel references
BASIC_1020_CHANNELS = [
    "Fp1", "Fp2", "F7", "F3", "Fz", "F4", "F8", "T3", "C3", "Cz",
    "C4", "T4", "T5", "P3", "Pz", "P4", "T6", "O1", "O2",
]
ADDITIONAL_SENSOR_CHANNELS = [
    "Fpz",
    "Oz",
    "Fp3",
    "Fp4",
    "F1",
    "F2",
    "AF3",
    "AF4",
    "AFz",
    "FT7",
    "FT8",
    "FC3",
    "FC4",
    "FCz",
    "C1",
    "C2",
    "CP3",
    "CP4",
    "CPz",
    "TP7",
    "TP8",
    "P1",
    "P2",
    "PO3",
    "PO4",
    "POz",
    "PO7",
    "PO8",
    "P5",
    "P6",
    "T7",
    "T8",
    "T9",
    "T10",
    "FT9",
    "FT10",
    "O9",
    "O10",
    "M1",
    "M2",
]
SENSOR_CHANNEL_NAMES = sorted(set(BASIC_1020_CHANNELS + ADDITIONAL_SENSOR_CHANNELS))

# Annotation label vocabularies
MOVEMENT_LABELS = (
    "bouge",
    "movement",
    "mouvement",
    "mouv",
    "mvts",
    "mvt",
    "mouvement ",
    "wiggle",
    "mouv de resp",
    "mvts paupieres",
    "mvt paupieres",
    "tape des mains",
    "donne des coups",
    "tape",
    "serre les poings",
    "serre les pojngs",
    "serrer le poing",
    "legers mouv des doigts",
    "legers mouv des mains",
    "leger mouv des doigts",
    "leger mouv des mains",
    "mains pt nerveux",
    "reviens sur le dos",
    "couche sur le dos",
    "couche cote",
    "couche cote d",
    "couchee cote g",
    "remet sur le dos",
    "s'assoit",
    "assoit",
    "ne veut pas rester coucher",
    "pt s'assoit",
    "gratte",
    "gratte l'epaule",
    "se gratte les yeux",
    "relache bras",
    "relache",
    "ouge",
    "timule",
    "sur le dos",
    "installe pt assis",
    "installe pt assis",
    "installe patient assis",
    "sur le dos",
    "enleve main sous la tete",
    "debranche le lit",
    "baisse le masque",
    "sursaut",
)
ARTEFACT_LABELS = (
    "artefact",
    "artefacts",
    "artifact",
    "artifacts",
    "artefatc",
    "arteafct",
    "atefact",
    "bruit",
    "bruit exterieur",
)
EFFORT_LABELS = (
    "effort",
    "Bon effot",
    "bbonn effforrt",
    "bon rffort",
    "bon effrt",
    "bbonn effforrt",
    "bonne efforr",
)
PAT_MONTAGE_LABELS = ("pat montage",)
HV_LABELS = ("hv",)
PHOTO_LABELS = ("photo",)
YAWN_COUGH_LABELS = (
    "baille",
    "baile",
    "bille",
    "baille:",
    "baile:",
    "yawn",
    "yawning",
    "tousse",
    "tousse trop",
    "patiente tousse",
    "cough",
    "coughing",
    "eternue",
    "eternu",
    "sneeze",
)
SLEEPY_LABELS = (
    "somnolence",
    "somnolence?",
    "somnolent",
    "somnolente",
    "somnoler",
    "somnole",
    "sommeil?",
    "semble vouloir sendormir",
    "semble vouloir s'endormir",
    "laisse pt somnoler",
    "sli meme si te dort",
    "pte se dit fatiguee",
    "pte se dit fatiguee depuis ce am",
    "privation de sommeil",
    "privation sommeil",
)
SLEEP_LABELS = (
    "dort",
    "dort?",
    "dort pendant eeg",
    "reste sur le dos pour dormir",
    "installe pour dormir",
    "se tourne pour dormir",
    "sleep",
    "asleep",
    "no sleep",
    "reste pour dormir",
    "prepare pour dormir",
    "patiente enleve ses bottes pour dormir",
)
COLLABORATION_LABELS = (
    "peu de collaboration",
    "faible collaboration",
    "collabore peu",
    "collabore pas",
    "pas de collaboration",
    "aucune collaboration",
    "aucune collaboraton",
    "aucune collabortion",
    "collaboration moyenne",
    "collaboration reduite",
    "colaboreation reduite",
    "collaboration limite",
    "collabore + ou-",
    "collabore + ou -",
    "collabore peu selon maman",
    "collabore pas vraiment",
    "ne collabore pas",
    "ne collabore pas vraiment",
    "faible collab",
    "peu de collab",
    "pte collabore pas",
    "pte collabore peu",
    "collabore selon maman",
    "collabore peu tsa",
    "collabore peu adhd",
    "collabore un peu",
)
JAW_FACE_TENSION_LABELS = (
    "relaxe machoire",
    "relacher machoire",
    "relache machoire",
    "relache la machoire",
    "relacher la machoire",
    "serre machoire",
    "machoire tendu",
    "machoire tendue",
    "detendre la machoire",
    "detendre le visage",
    "relacher le visage",
    "relache visage",
    "relacher visage",
    "serre front",
    "serre le front",
    "seere front",
    "serre dents",
    "serre les dents",
)
SENSOR_ELECTRODE_VERBS = (
    "place",
    "ouche",
    "touche",
    "toucher",
    "retouche",
    "retoucher",
    "frotte",
    "frotter",
    "refrotte",
    "refrotter",
    "replace",
    "replacer",
    "change",
    "changer",
    "pont",
    "bridge",
    "pontage",
    "bris contact",
    "bris de contact",
    "filtre 60 hertz",
    "filtre 60hz",
    "filtre 60",
    "60hz",
    "60 hz",
    "change le ground",
    "change ground",
    "ground",
    "masse",
    "replace les fils",
    "retouche les electrodes",
    "refrotte fils",
    "replace electrode",
    "change electrode",
    "replace les electrodes",
    "retouche les fils",
    "tete mouillee",
    "t5ouche",
    "touvhe",
    "touhe",
    "arrange",
    "hange",
)

EMOTION_BEHAVIOR_LABELS = (
    "pleure",
    "pleur",
    "cri",
    "crie",
    "parle",
    "parle ",
    "parler",
    "parle beaucoup",
    "rit",
    "rie",
    "la pte rit",
    "la pte arret pas de rire",
    "bof",
    "tete qui tourne",
    "pte mal au ventre",
    "pt mal au ventre",
    "pt a tres mal au ventre pas d'hyper",
)
ORAL_ACTIVITY_LABELS = (
    "machonne",
    "machonnement",
    "pt machonne",
    "ouvre la bouche",
    "reniffle",
    "sucer",
    "suce fort",
    "suce son pouce",
    "prend la suce",
    "prend sa suce",
    "prend suce",
    "avale",
    "boit de l'eau",
    "boit de leau",
    "pte a le push button",
    "gavage en cours",
    "demande au patient de jeter sa gomme",
)
EYE_MOVEMENT_LABELS = (
    "cligne des yeux",
    "revulsion des yeux",
    "impossible de fermer les yeux",
    "impossible de lui faire ouvrir les yeux",
    "ne veut pas fermer les yeux",
    "ne veut pas ferme ses yeux",
    "ne ferme pas les yeux",
    "ouvre et ferme les yeux",
    "ouvre et ferme les yeux souvent",
    "ouvre yeux",
    "ouvre les yeux",
    "yeux ouvres et fermes",
    "yeux mi-clos",
    "yeux semi-ouvert",
    "yeux semi ouvert",
    "yeux semi ouverts",
    "yeux semi ouvert",
    "yeux semi",
    "les yeux sont fermes par maman",
    "tres difficile de fermer les yeux",
    "incapable de fermer les yeux",
    "essaye douvrir les yeux",
    "impossible de fermer les yeux",
    "yeux vers la d",
)
WAKEFULNESS_LABELS = (
    "se reveille",
    "se revelle",
    "reveille la pte",
    "reveille pt",
    "reveille le pt",
    "reveille le pt",
    "reveille la petite",
    "reville la pte",
    "reville la pt",
    "reveille la pt",
    "reveille le patient",
    "pte reveiller",
    "tente de reveiller",
    "tente de reveiller la pte",
    "tente de reveiller pt",
    "va reveiller pt",
    "reveille pt",
    "reveiller",
    "tente reveiller pte",
    "tente reveiller la pte",
    "reveil pt",
    "reveil la pte",
)
RESPIRATION_LABELS = (
    "arret des respirations",
    "arret respiration",
    "arrete de respirer",
    "reprise des respirations",
    "reprise des repirations",
    "reprise respiration",
    "reprend respiration",
)


def _build_sensor_patterns() -> Tuple[str, ...]:
    patterns = set(SENSOR_ELECTRODE_VERBS)
    lower_channels = {ch.lower() for ch in SENSOR_CHANNEL_NAMES}
    for verb in SENSOR_ELECTRODE_VERBS:
        for ch in lower_channels:
            patterns.add(f"{verb} {ch}")
    return tuple(sorted(patterns))


SENSOR_ELECTRODE_LABELS = _build_sensor_patterns()
SENSOR_CHANNEL_TOKEN_SET = {ch.lower() for ch in SENSOR_CHANNEL_NAMES}
SENSOR_ACTION_KEYWORDS = (
    "touche",
    "toucher",
    "retouche",
    "retoucher",
    "frotte",
    "frotter",
    "refrotte",
    "refrotter",
    "replace",
    "replacer",
    "change",
    "changer",
    "pont",
    "bridge",
    "pontage",
    "bris contact",
    "bris de contact",
    "filtre 60",
    "60hz",
    "60 hz",
    "ground",
    "masse",
    "t5ouche",
    "touvhe",
    "touhe",
    "arrange",
    "hange",
)

ANNOTATION_INTEREST_MAP = {
    "Eyes Open": EYES_OPEN_LABELS,
    "Eyes Closed": EYES_CLOSED_LABELS,
    "Movement": MOVEMENT_LABELS,
    "Artefact": ARTEFACT_LABELS,
    "Effort": EFFORT_LABELS,
    "PAT Montage": PAT_MONTAGE_LABELS,
    "HV": HV_LABELS,
    "PHOTO": PHOTO_LABELS,
    "Yawning/Coughing": YAWN_COUGH_LABELS,
    "Sleepy": SLEEPY_LABELS,
    "Sleep": SLEEP_LABELS,
    "Sensor/Electrode": SENSOR_ELECTRODE_LABELS,
    "Jaw/Face Tension": JAW_FACE_TENSION_LABELS,
    "Collaboration": COLLABORATION_LABELS,
    "Emotion/Behavior": EMOTION_BEHAVIOR_LABELS,
    "Oral Activity": ORAL_ACTIVITY_LABELS,
    "Eye Movement": EYE_MOVEMENT_LABELS,
    "Wakefulness": WAKEFULNESS_LABELS,
    "Respiration": RESPIRATION_LABELS,
}

CLINICAL_COMMENT_LABELS = {
    "Clinical - Spikes": (
        "pointe-lente",
        "pointe?",
        "vertex pointu",
        "vertex pointus",
        "vertex pointu?",
        "spike",
        "spike?",
        "b9 spike",
        "posts",
        "posts?-->",
        "polypp",
        "polypp ftg",
        "pfd",
        "ppd",
        "pcd",
        "pfd?",
        "ppd?",
        "pcd?",
        "spindle?",
        "spindle",
        "posts?",
        "vertex",
    ),
    "Clinical - Slowing": (
        "delta",
        "delta frontal",
        "delta front raide",
        "frontal delta",
        "ralentissement",
        "ralentissement diffus",
        "ralentissement diffus asynchrone",
        "lent ",
        "slowing",
        "lpq slowing",
        "lent temp",
        "lent diffus",
        "lent persiste",
        "lent ft",
        "lent d",
        "gene-frontal",
        "lent un peu asym",
    ),
    "Clinical - Seizure": (
        "crise",
        "absence",
        "absemce",
        "absence?",
        "pte absence",
        "episode",
        "episode clinique",
        "spasme",
        "spasmes",
        "spasme pied",
        "spasme bras",
        "myoclonie",
        "myclonie",
        "mioclonie",
        "petite crise",
        "possiblement clinique",
        "pte crise",
        "dissociation",
    ),
    "Clinical - Background": (
        "pdr",
        "pdr 10",
        "pdr 11",
        "pdr 11-12",
        "posts",
        "mu?",
        "pswy",
        "background",
    ),
}

IGNORED_DEMOGRAPHIC_LABELS = (
    "13",
    "17",
    "garcon de 9 abns"
    "garcon",
    "fille",
    "fillette",
    "adolescent",
    "adolescente",
    "garcon de",
    "fille de",
    "adolescent de",
    "adolescente de",
    "jeune garcon",
    "jeune fille",
    "grcon de",
    "folle de",
    "6 ans gracon",
    "gartcon de",
    "garson de",
    "garson de 16ans",
    "garon de",
    "garcon de 9",
    "garcon de 9 abns",
    "garcon de 11a",
    "garon de 12 ans",
    "garon de 12ans",
    "garcon de 12 ans",
    "garcon de 11 ans",
    "rcon de 11 ans",
    "rcon de 10 ans",
    "pt de 10 ans",
    "pte de 18 ans",
    "pt de 10",
    "pt de ",
    "pte de ",
    "rcon de",
    "e 17 ans",
    "e 16 ans",
    "e 10 ans",
    "ado de 17 ans",
    "11 ans",
    "13 ans",
    "17 ans",
    "15 ans",
    "12 ans",
)

KNOWN_EVENT_LABELS = set(ANNOTATION_INTEREST_MAP.keys()) | set(CLINICAL_COMMENT_LABELS.keys())
REFERENCE_EVENT_KEYWORDS = ("a1+a2 off",)
AGE_YEARS_PATTERN = re.compile(r"\b\d{1,2}\s*ans\b")
DIGIT_PATTERN = re.compile(r"\d+")

HV_LABELS = ("hv",)
POST_HV_LABELS = ("post hv",)
PHOTO_LABELS = ("photo",)

SEGMENT_COLUMNS = [
    "segment_type",
    "t_start",
    "t_stop",
    "duration",
    "freq_hz",
    "hv_index",
    "post_hv_index",
    "eyes_open_duration",
    "eyes_closed_duration",
]

PHOTO_FREQ_PATTERN = re.compile(r"(\d+(?:\.\d+)?)\s*hz", flags=re.IGNORECASE)

__all__ = [
    "ADDITIONAL_SENSOR_CHANNELS",
    "AGE_YEARS_PATTERN",
    "ANNOTATION_INTEREST_MAP",
    "ARTEFACT_LABELS",
    "BAND_LIMITS",
    "BASIC_1020_CHANNELS",
    "CLINICAL_COMMENT_LABELS",
    "COLLABORATION_LABELS",
    "DIGIT_PATTERN",
    "EFFORT_LABELS",
    "EMOTION_BEHAVIOR_LABELS",
    "EYE_MOVEMENT_LABELS",
    "EYES_CLOSED_LABELS",
    "EYES_OPEN_LABELS",
    "HV_LABELS",
    "IGNORED_DEMOGRAPHIC_LABELS",
    "JAW_FACE_TENSION_LABELS",
    "KNOWN_EVENT_LABELS",
    "MOVEMENT_LABELS",
    "ORAL_ACTIVITY_LABELS",
    "PAT_MONTAGE_LABELS",
    "PHOTO_LABELS",
    "REFERENCE_EVENT_KEYWORDS",
    "RESPIRATION_LABELS",
    "SENSOR_ACTION_KEYWORDS",
    "SENSOR_CHANNEL_NAMES",
    "SENSOR_CHANNEL_TOKEN_SET",
    "SENSOR_ELECTRODE_LABELS",
    "SENSOR_ELECTRODE_VERBS",
    "SLEEP_LABELS",
    "SLEEPY_LABELS",
    "WAKEFULNESS_LABELS",
    "YAWN_COUGH_LABELS",
    "POST_HV_LABELS",
    "SEGMENT_COLUMNS",
    "PHOTO_FREQ_PATTERN",
]
